### ISSUE TITLE
Has it been tested?

### ISSUE THREAD

**Issue by BarbzYHOOL** [mindsear/TemplateNPC-azerothzore#1]
I asked one of AzerothCore team member to test it and it was not working correctly. (Not much more info to give because I haven't tested myself yet)

We wanted to make it full modular, so without the need for a .patch

If you're interested you can hop on our discord because that module seems sick!

**Comment by WarTey** [comment]
Hi, I just test it but I get multiples errors during compilation... I know where is the problem so I will try to fix it and post it if it work.

**Comment by BarbzYHOOL** [comment]
Hey @WarTey refer to this fork instead https://github.com/azerothcore/WIP-mod-npc-talent-template

**Comment by ELdoBA** [comment]
Will be great if he can make it without patch for AC :+1:
